### PR TITLE
Add src and out

### PR DESCRIPTION
**Pull request by jonkwheeler**
I went ahead and fixed up the directories and logging. You no longer have to provide the `--src` or `--out`, and there are logs to warn you.

In addition, there was too many logs, so I disabled them unless on the `--verbose` flag.

Below is an example of myself compiling to show you the logs now, without `-v`.

tscpath-logging 2019-05-08 12_33_11

Hoping to get this merged asap. Thanks @joonhocho !

[Treat](https://media3.giphy.com/media/Q6gPyUYrCk76g/200w.gif?cid=c94812d05cd2c07439726b525122187f&rid=200w.gif)

### CODE REVIEW

**Review by vladjerca — COMMENTED** [review]
Rather than checking the `verbose` flag everywhere. I guess we could just create an internal util:

```
const log = (msg) => verbose && console.log(msg)
```

It would be much easier this way.

I think this is a great addition nonetheless, hope it gets merged soon xD

**Comment by jonkwheeler** [comment]
Yeah, would be a bit cleaner

**Comment by jonkwheeler** [comment]
Donzo 🧙‍♂️

**Review by vladjerca — APPROVED** [review]
🖖

**Comment by joonhocho** [comment]
Sorry, but I've reverted these changes.
I am not sure if you have tested the code on many projects with different directory structures, but last time I tried to use paths from tsconfig, it did not work for some project settings.
As far as I remember, sometimes the output directory did not match how source directory is structured.

**Comment by jonkwheeler** [comment]
Yeah, I tested it. I showed it working in the gif attached to the first comment on this PR.

What are you running?

**Comment by joonhocho** [comment]
@jonkwheeler What I am saying is, it may work for one setting, but may not for another. It depends on how project is structured. Typescript does weird thing to determine output directory structure. I need to have some time invested if I want to have this feature merged and test more. I originally try to have this feature but gave up at the time.

**Comment by jonkwheeler** [comment]
The current logic requires you supply a tsconfig. From that it first checks to see if you have a `--src` and `--out`, and if so, uses them, otherwise it'll use the `rootDir` and `outDir` specified in the tsconfig. If neither are provided, it'll error out.

**Comment by jplew** [comment]
@jonkwheeler I tested your branch and it works for me, logging changes are nice too.

To be clear, is the `--src` flag mandatory? When I omit that flag I get a `'--src must be specified')` error, even if I specify a `rootDir`. Are you making an attempt to infer the src directory based on `rootDir`?

**Comment by jonkwheeler** [comment]
You do? That's strange. I do not. I'll have to test again, but I'm able to do it without flagging it. Make sure you have `tsconfig.compilerOptions.rootDir`, and not `tsconfig.rootDir, (just double checking 🤠).

**Comment by jplew** [comment]
don't have time to look at your code right now, but I'm trying this: `tscpaths -p src/tsconfig.json`. `.src/tsconfig.json` is extending my base `./tsconfig.json`. Not sure if that has anything to do with it.

**Comment by jonkwheeler** [comment]
Extending doesn't work for getting the directories. You have to specify it in the exact config file you are referencing. I don't have a good reason why, it just won't grab the directories from an extended config. You can still use a second extended config file, but you have to set the `rootDir` and `ourDir` in there. Was annoying to me too.

**Comment by jonkwheeler** [comment]
wonder if we detect the extend key, and then go to that file instead... 😑

**Comment by vladjerca** [comment]
@joonhocho the changes in this PR do not affect the previous behavior of the lib, reverting the changes makes no sense 😔.

@jonkwheeler I think this PR should be opened again...

As for the extended configs, that could be solved by recursively loading the parent configs until the properties are found or the top node is reached...

**Comment by jonkwheeler** [comment]
Can we reopen this?

**Comment by jonkwheeler** [comment]
I've got all of this working beautifully I think.

When no flags are set...

```
Using tsconfig: /Users/jonwheeler/invision_code/eos-ds/tsconfig.types.json
Using compilerOptions.rootDir from your tsconfig
Using src: /Users/jonwheeler/folder/src
Using compilerOptions.outDir from your tsconfig
Using out: /Users/jonwheeler/folder/dist
Successfully resolved 70 paths with tscpaths.
```

otherwise

```
Using tsconfig: /Users/jonwheeler/invision_code/eos-ds/tsconfig.types.json
Using flag --src
Using src: /Users/folder/src
Using flag --out
Using out: /Users/jonwheeler/folder/dist
Successfully resolved 70 paths with tscpaths.
```

**Comment by jonkwheeler** [comment]
I fixed this all in https://github.com/joonhocho/tscpaths/pull/12

**Pull request merged**
